import Head from "next/head";
import About from "@/components/About";

export default function aboutPages() {
  return (
    <>
      <Head>
        <title>About Twite Soft</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <About />
      </div>
    </>
  );
}
