import Contact from "@/components/Contact";
import Head from "next/head";

export default function contactPages() {
  return (
    <>
      <Head>
        <title>Contact Twite Soft</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <Contact />
      </div>
    </>
  );
}
