import Head from "next/head";

import Home from "@/components/Home";
import About from "@/components/About";
import Services from "@/components/Services";
import Projects from "@/components/Projects";
import Pricing from "@/components/Pricing";
import Team from "@/components/Team";
import Contact from "@/components/Contact";

export default function index() {
  return (
    <>
      <Head>
        <title>Twite Soft</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <Home />

        <About />

        <Services />

        <Projects />

        <Pricing />

        <Team />

        <Contact />
      </div>
    </>
  );
}
