import Head from "next/head";
import Image from "next/image";
import Link from "next/link";

import teamImg1 from "/public/images/team/team1.jpg";
import teamImg2 from "/public/images/team/team2.jpg";
import teamImg3 from "/public/images/team/team3.jpg";
import teamImg4 from "/public/images/team/team4.jpg";
import teamImg5 from "/public/images/team/team5.webp";

import contactImage from "/public/images/contact.svg";

import Home from "@/components/Home";
import About from "@/components/About";
import Services from "@/components/Services";
import Projects from "@/components/Projects";
import Pricing from "@/components/Pricing";

export default function index() {
  return (
    <>
      <Head>
        <title>Twite Soft</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        {/*--====== PRELOADER PART START ======--*/}

        <div className="preloader">
          <div className="loader">
            <div className="ytp-spinner">
              <div className="ytp-spinner-container">
                <div className="ytp-spinner-rotator">
                  <div className="ytp-spinner-left">
                    <div className="ytp-spinner-circle"></div>
                  </div>
                  <div className="ytp-spinner-right">
                    <div className="ytp-spinner-circle"></div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>

        {/*--====== PRELOADER PART ENDS ======--*/}

        {/*--------- HEADER PART Start------------ */}
        <Home />
        {/*--------- HEADER PART End------------ */}

        {/*--====== ABOUT PART START ======--*/}
        <About />
        {/*--====== ABOUT PART ENDS ======--*/}

        {/*--====== SERVICES PART START ======--*/}
        <Services />

        {/*--====== SERVICES PART ENDS ======--*/}

        {/*-------------------------- PROJECTS PART START------------ */}
        <Projects />
        {/*-------------------------- PROJECTS PART END------------ */}

        {/*--====== PRICING PLAN PART START ======--*/}
        <Pricing />
        {/*--====== PRICING PLAN PART ENDS ======--*/}

        {/*--====== TEAM PART START ======---------*/}

        <section id="team" className="team_area bg-gray pt-120 pb-120">
          <div className="container">
            <div className="row justify-center">
              <div className="w-full lg:w-1/2">
                <div className="section_title text-center pb-6">
                  <h5 className="sub_title">Team</h5>
                  <h4 className="main_title">Meet Our Team Members</h4>
                </div>
              </div>
            </div>
            <div className="team-wrapper relative">
              <div className="row team_active">
                <div className="w-full sm:w-10/12 md:w-6/12 lg:w-4/12">
                  <div className="single_team_item mx-auto">
                    <div className="single_team mx-3">
                      <div className="team_image relative">
                        <Image src={teamImg1} alt="team image" className="w-full" />
                        <ul className="social absolute top-4 right-8">
                          <li>
                            <a href="#">
                              <i className="lni lni-facebook-filled"></i>
                            </a>
                          </li>
                          <li>
                            <a href="#">
                              <i className="lni lni-twitter-filled"></i>
                            </a>
                          </li>
                          <li>
                            <a href="#">
                              <i className="lni lni-linkedin-original"></i>
                            </a>
                          </li>
                        </ul>
                      </div>
                      <div className="team_content py-5 px-8 relative">
                        <h4 className="team_name text-xl md:text-2xl">
                          <a href="#" className="text-black group-hover:text-white">
                            Al-Mamun Sarkar
                          </a>
                        </h4>
                        <p className="mt-2 transition-all duration-300 group-hover:text-white">
                          Founder and CEO
                        </p>
                      </div>
                    </div>
                  </div>
                </div>
                <div className="w-full sm:w-10/12 md:w-6/12 lg:w-4/12">
                  <div className="single_team_item mx-auto">
                    <div className="single_team mx-3">
                      <div className="team_image relative">
                        <Image src={teamImg2} alt="team image" className="w-full" />
                        <ul className="social absolute top-4 right-8">
                          <li>
                            <a href="#">
                              <i className="lni lni-facebook-filled"></i>
                            </a>
                          </li>
                          <li>
                            <a href="#">
                              <i className="lni lni-twitter-filled"></i>
                            </a>
                          </li>
                          <li>
                            <a href="#">
                              <i className="lni lni-linkedin-original"></i>
                            </a>
                          </li>
                        </ul>
                      </div>
                      <div className="team_content py-5 px-8 relative">
                        <h4 className="team_name text-xl md:text-2xl">
                          <a href="#" className="text-black group-hover:text-white">
                            Abdur Rahman
                          </a>
                        </h4>
                        <p className="mt-2 transition-all duration-300 group-hover:text-white">
                          Co-Founder and Project manager
                        </p>
                      </div>
                    </div>
                  </div>
                </div>
                <div className="w-full sm:w-10/12 md:w-6/12 lg:w-4/12">
                  <div className="single_team_item mx-auto">
                    <div className="single_team mx-3">
                      <div className="team_image relative">
                        <Image src={teamImg3} alt="team image" className="w-full" />
                        <ul className="social absolute top-4 right-8">
                          <li>
                            <a href="#">
                              <i className="lni lni-facebook-filled"></i>
                            </a>
                          </li>
                          <li>
                            <a href="#">
                              <i className="lni lni-twitter-filled"></i>
                            </a>
                          </li>
                          <li>
                            <a href="#">
                              <i className="lni lni-linkedin-original"></i>
                            </a>
                          </li>
                        </ul>
                      </div>
                      <div className="team_content py-5 px-8 relative">
                        <h4 className="team_name text-xl md:text-2xl">
                          <a href="#" className="text-black group-hover:text-white">
                            Md. Tipu Sultan
                          </a>
                        </h4>
                        <p className="mt-2 transition-all duration-300 group-hover:text-white">
                          Co-Founder and Tech Lead
                        </p>
                      </div>
                    </div>
                  </div>
                </div>
                <div className="w-full sm:w-10/12 md:w-6/12 lg:w-4/12">
                  <div className="single_team_item mx-auto">
                    <div className="single_team mx-3">
                      <div className="team_image relative">
                        <Image src={teamImg4} alt="team image" className="w-full" />
                        <ul className="social absolute top-4 right-8">
                          <li>
                            <a href="#">
                              <i className="lni lni-facebook-filled"></i>
                            </a>
                          </li>
                          <li>
                            <a href="#">
                              <i className="lni lni-twitter-filled"></i>
                            </a>
                          </li>
                          <li>
                            <a href="#">
                              <i className="lni lni-linkedin-original"></i>
                            </a>
                          </li>
                        </ul>
                      </div>
                      <div className="team_content py-5 px-8 relative">
                        <h4 className="team_name text-xl md:text-2xl">
                          <a href="#" className="text-black group-hover:text-white">
                            Md. Rajib Mia Rahid
                          </a>
                        </h4>
                        <p className="mt-2 transition-all duration-300 group-hover:text-white">
                          Web Application Developer
                        </p>
                      </div>
                    </div>
                  </div>
                </div>
                <div className="w-full sm:w-10/12 md:w-6/12 lg:w-4/12">
                  <div className="single_team_item mx-auto">
                    <div className="single_team mx-3">
                      <div className="team_image relative">
                        <Image src={teamImg5} alt="team image" className="w-full" />
                        <ul className="social absolute top-4 right-8">
                          <li>
                            <a href="#">
                              <i className="lni lni-facebook-filled"></i>
                            </a>
                          </li>
                          <li>
                            <a href="#">
                              <i className="lni lni-twitter-filled"></i>
                            </a>
                          </li>
                          <li>
                            <a href="#">
                              <i className="lni lni-linkedin-original"></i>
                            </a>
                          </li>
                        </ul>
                      </div>
                      <div className="team_content py-5 px-8 relative">
                        <h4 className="team_name text-xl md:text-2xl">
                          <a href="#" className="text-black group-hover:text-white">
                            Md. Alamin Islam
                          </a>
                        </h4>
                        <p className="mt-2 transition-all duration-300 group-hover:text-white">
                          Full Stack Developer
                        </p>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </section>

        {/*--====== TEAM PART ENDS ======---------*/}

        {/*--====== CONTACT PART START ======---------*/}
        <section id="contact" className="contact_area relative pt-18 pb-120">
          <div className="contact_image flex items-center justify-end">
            <div className="image lg:pr-13">
              <Image src={contactImage} alt="contact-image" />
            </div>
          </div>

          <div className="container">
            <div className="row justify-end">
              <div className="w-full lg:w-1/2">
                <div className="contact_wrapper mt-11">
                  <div className="section_title pb-4">
                    <h5 className="sub_title">Contact</h5>
                    <h4 className="main_title">Get In Touch</h4>
                  </div>

                  <div className="contact_form">
                    <form id="contact-form" action="" method="POST">
                      <div className="row">
                        <div className="w-full md:w-1/2">
                          <div className="mx-3">
                            <div className="single_form mt-8">
                              <input
                                name="name"
                                id="name"
                                type="text"
                                placeholder="Name"
                                className="w-full rounded-md py-4 px-6 border border-solid border-body-color"
                              />
                            </div>
                          </div>
                        </div>
                        <div className="w-full md:w-1/2">
                          <div className="mx-3">
                            <div className="single_form mt-8">
                              <input
                                name="email"
                                id="email"
                                type="email"
                                placeholder="Email"
                                className="w-full rounded-md py-4 px-6 border border-solid border-body-color"
                              />
                            </div>
                          </div>
                        </div>
                        <div className="w-full">
                          <div className="mx-3">
                            <div className="single_form mt-8">
                              <textarea
                                name="message"
                                id="message"
                                placeholder="Message"
                                rows="5"
                                className="w-full rounded-md py-4 px-6 border border-solid border-body-color resize-none"
                              ></textarea>
                            </div>
                          </div>
                        </div>
                        <p className="form-message mx-3"></p>
                        <div className="w-full">
                          <div className="mx-3">
                            <div className="single_form mt-8">
                              <button type="submit" className="main-btn contact-btn">
                                Submit
                              </button>
                            </div>
                          </div>
                        </div>
                      </div>
                    </form>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </section>
        {/*--====== CONTACT PART ENDS ======---------*/}

        {/*--====== FOOTER PART START ======---------*/}

        {/*--====== FOOTER PART ENDS ======---------*/}
      </div>
    </>
  );
}
