import Projects from "@/components/Projects";
import Head from "next/head";

export default function projectPages() {
  return (
    <>
      <Head>
        <title>Project Twite Soft</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="page">
        <Projects />
      </div>
    </>
  );
}
